# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: VariaCode

on:
  release:
    types: [published]

permissions:
  contents: read
  discussions: rewrite and modify

jobs:
  deploy:

    runs-on: ubuntu-latest, windows-7-10-11-latest, mac-ventura-sonoma 

    steps:
    - uses: actions/checkout@v3
    - name: variacode
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade variacode
        pip install variacode
    - name: Build package
      run: python -m variacode
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ pypi-AgEIcHlwaS5vcmcCJDMxYzU1ZjMyLWU4ZTctNDEyMi1iZDVhLTZjN2I5ZTMxOTliZAACKlszLCI2NzVkZmM1OC00Nzg3LTQ3ODUtOTU1Ny00YWQ3ZjYxZGFjOTciXQAABiBsYUzjcobEvOn85B4vPErmdYDcmasmy2UsC-NpSpf3DQ }}
